# Generated by Django 5.2.5 on 2025-09-03 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'cat_categorias',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='CatContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(db_index=True, max_length=150)),
                ('apellido_paterno', models.CharField(max_length=150)),
                ('apellido_materno', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('telefono_oficina', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_personal', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, db_index=True, max_length=255, null=True)),
                ('puesto', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo', models.CharField(choices=[('OIC', 'OIC'), ('Tecnico', 'Técnico'), ('Sindico', 'Síndico'), ('PM', 'PM'), ('Otro', 'Otro')], default='Otro', max_length=20)),
                ('otro', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'cat_contactos',
                'ordering': ['apellido_paterno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='CatRespuestaDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('respuesta', models.TextField()),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Respuesta default',
                'verbose_name_plural': 'Respuestas default',
                'db_table': 'cat_respuestas_default',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='CatEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_municipio', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('personalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('patrimonio', models.CharField(blank=True, max_length=255, null=True)),
                ('base_legal', models.CharField(blank=True, max_length=255, null=True)),
                ('ambito_gobierno', models.CharField(blank=True, max_length=100, null=True)),
                ('poder', models.CharField(blank=True, max_length=100, null=True)),
                ('clasificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('servidores_publicos', models.IntegerField(default=0)),
                ('control_tribunal', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('contacto_oic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacto_oic', to='sitio.catcontacto')),
                ('contacto_tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacto_tecnico', to='sitio.catcontacto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'db_table': 'cat_entidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='catcontacto',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidad', to='sitio.catentidad'),
        ),
        migrations.CreateModel(
            name='EntidadSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuente', models.CharField(choices=[('SESAJ', 'SESAJ'), ('SEPIFAPE', 'SEPIFAPE'), ('Propio', 'Propio')], max_length=20)),
                ('operacion_modo', models.CharField(choices=[('online', 'Online'), ('local', 'Local'), ('multiente', 'Multiente')], max_length=20)),
                ('sistema', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6')], max_length=5)),
                ('activo', models.BooleanField(default=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidad_relacion', to='sitio.catentidad')),
            ],
            options={
                'verbose_name': 'Entidad Sistema',
                'verbose_name_plural': 'Entidades Sistema',
                'db_table': 'sige_entidades_sistema',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_solicitud', models.DateField()),
                ('folio', models.CharField(max_length=100, unique=True)),
                ('tipo_solicitud', models.CharField(max_length=150)),
                ('quien_recibe_ost', models.CharField(blank=True, max_length=255, null=True)),
                ('impreso', models.BooleanField(default=False)),
                ('quien_recibe_dtp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quien_recibe_dtp', to=settings.AUTH_USER_MODEL)),
                ('entidad_sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidad_sistema', to='sitio.entidadsistema')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'cat_solicitudes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_evento', models.CharField(choices=[('cambio_datos', 'Cambio de datos'), ('llamada_informativa', 'Llamada informativa'), ('llamada_tarea', 'Llamada con tarea pendiente'), ('ticket_creado', 'Ticket creado'), ('ticket_actualizado', 'Ticket actualizado'), ('pdn', 'Seguimeinto conexión PDN')], max_length=50)),
                ('descripcion', models.TextField()),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_autor', to=settings.AUTH_USER_MODEL)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_contacto', to='sitio.catcontacto')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidad_historicos', to='sitio.catentidad')),
            ],
            options={
                'verbose_name': 'Histórico',
                'verbose_name_plural': 'Históricos',
                'db_table': 'historico',
                'ordering': ['-created_at'],
            },
        ),
    ]
