# Generated by Django 5.2.5 on 2025-09-03 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historico',
            table='sige_historico',
        ),
    ]
