# Generated by Django 5.2.5 on 2025-09-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_alter_historico_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catcategoria',
            options={'ordering': ['titulo'], 'verbose_name': 'Catálogo Categoría', 'verbose_name_plural': 'Catálogo Categorías'},
        ),
        migrations.AlterModelOptions(
            name='catcontacto',
            options={'ordering': ['apellido_paterno', 'nombres'], 'verbose_name': 'Catálogo Contacto', 'verbose_name_plural': 'Catálogo Contactos'},
        ),
        migrations.AlterModelOptions(
            name='catentidad',
            options={'ordering': ['nombre'], 'verbose_name': 'Catálogo Entidad', 'verbose_name_plural': 'Catálogo Entidades'},
        ),
        migrations.AlterModelOptions(
            name='catrespuestadefault',
            options={'ordering': ['titulo'], 'verbose_name': 'Catálogo Respuesta default', 'verbose_name_plural': 'Catálogo Respuestas default'},
        ),
        migrations.AlterModelOptions(
            name='catsolicitud',
            options={'ordering': ['-created_at'], 'verbose_name': 'Catálogo Solicitud', 'verbose_name_plural': 'Catálogo Solicitudes'},
        ),
        migrations.AddField(
            model_name='entidadsistema',
            name='api_auth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entidadsistema',
            name='api_clien_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entidadsistema',
            name='api_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entidadsistema',
            name='api_declaraciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entidadsistema',
            name='api_grant_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entidadsistema',
            name='api_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entidadsistema',
            name='api_scope',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entidadsistema',
            name='api_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entidadsistema',
            name='cantidad_declaraciones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entidadsistema',
            name='licencia',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='entidadsistema',
            name='operacion_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entidadsistema',
            name='sistema_operativo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entidadsistema',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catsolicitud',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catsolicitud',
            name='folio',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='catsolicitud',
            name='tipo_solicitud',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='entidadsistema',
            name='fuente',
            field=models.CharField(blank=True, choices=[('SESAJ', 'SESAJ'), ('SEPIFAPE', 'SEPIFAPE'), ('Propio', 'Propio')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entidadsistema',
            name='operacion_modo',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('local', 'Local'), ('multiente', 'Multiente')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entidadsistema',
            name='sistema',
            field=models.CharField(blank=True, choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6')], max_length=5, null=True),
        ),
    ]
