# Generated by Django 5.2.5 on 2025-09-03 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ticket',
            table='helpdesk_tickets',
        ),
        migrations.AlterModelTable(
            name='ticketsseguimiento',
            table='helpdesk_tickets_seguimiento',
        ),
    ]
